### ISSUE TITLE
Accept input from stdin

### ISSUE THREAD

**Issue by jcbeukes** [jerometwell/pynonymizer#16]
The project is awesome! Thanks for all your hard work. 

It would be really cool if you could accept input from stdin though. That way we could use it as part of a pipe!
Would you be able to add that please?

**Comment by jerometwell** [comment]
Sounds like a useful suggestion for automation projects! ✨

Can you give me an example of how the interface might work? I assume you were thinking of piping the sql dump directly from mysqldump or cat'ing a file:

```
mysqldump | pynonymizer 

```

I can say with some certainty that this is essentially only going to be available to mysql/postgresql, because of the way the mssql integration works. Not sure if it affects you, but it's worth saying.

**Comment by jcbeukes** [comment]
Hi, thanks for your fast reply!

Yeah, we're using mysql. So we'd like to ssh mysqldump... ... | panonamizer --input -
That way we don't have to have an un-anonymized data dump on our local computer.

**Comment by jerometwell** [comment]
This is such a good idea!!! 🥳
it paves the way for all kinds of stuff i was originally going to have to abstract behind a load of command line options. I need to bake this into more tools! 

The interface will be `--input -` and i've also added `--output -` for stdout, since what's a pipe without both ends! 

I've created PR #17 for this. 

This should go out with 1.12.0 after merging.

**Comment by jerometwell** [comment]
please test in `v1.12.0` and let me know if there's anything i've missed. https://pypi.org/project/pynonymizer/1.12.0/

**Comment by jcbeukes** [comment]
Awesome! Thanks so much. I'll test it and let you know!
