### ISSUE TITLE
MSSQL [Feature request]: Using remote SQL when restore and backup steps are skipped

### ISSUE THREAD

**Issue by kine** [jerometwell/pynonymizer#45]
We are using pynonymizer to anonymize data in Customer's MS SQL database before it is transferred to our infrastructure for support/development purposes. We cannot do that in our infrastructure because GDPR. We cannot install python on Customer's server. But we have access to the SQL through VPN. 

Solution is to not force using local server only, if only anonymization step is running through using 
```
start_at_step='ANONYMIZE_DB',stop_at_step='ANONYMIZE_DB'
```

I had tested that with success when I removed the check for db_host being None and removing the db_host = "(local)" (for testing purposes without any condition if the ANONYMIZE_DB step is only running).

**Comment by jerometwell** [comment]
Phew 😅 thanks for your work reporting. I support this use case! the mssql provider needs some love. 

I'm going to be looking at this over the next week or so but I'm happy to talk about suggestions or contributions. 

 I think that the way you're using the tool is subtly linked to #31 , since the CLI features aren't really of use to you.

**Comment by jerometwell** [comment]
This should be fixed by #52 ! I've got some other things to look at but this should go out with v1.18.0 over the next week or so. 

If you can provide feedback against master pre-release, it would be helpful 😇

**Comment by jerometwell** [comment]
Sent this change out with v1.18.0 ! https://pypi.org/project/pynonymizer/1.18.0/
